### PR TITLE
Issue 34 Web API Core Tests

### PR DESCRIPTION
**Pull request by darnjo**
Adds Web API 1.0.2 Core Server automated testing, including Collections Support, to the Commander.
The Commander assumes `Collection(Edm.EnumType)` by default for multiple enumerations. Those using `IsFlags="true"` can pass `-DuseCollections=false`. 

See #34 and README for more information. 

TODO: still need to add all-in-one pretty reporting task for Web API before PR.

### CODE REVIEW

**Review by EnFinlay — APPROVED** [review]
There are far too many changes for me to give a thorough review of every single one. In general all the changes appear to be in line with decisions made in the Certification subgroup and the Transport workgroup.

One suggestion - could the `odata-openapi` folder be included as a git submodule?

**Comment by darnjo** [comment]
Thanks for the review, Eric. This codebase is based on the Web API "Gold" automated testing code, which had 
previouly been used to certify live servers. "Core" changed some of the existing tests and added a couple of new ones, but the underlying glue code is largely the same. 

Good suggestion regarding making the `odata-openapi` project a submodule. I'll take care of that before merging. I'm also making an all-in-one testing and reporting task similar to the DD test code, which I'll provide instructions in the README for.

**Comment by EnFinlay** [comment]
Sounds good!

**Comment by darnjo** [comment]
Merging. Will handle change to `all()` test in subsequent issue/PR.

**Pull request merged**
